"""Add 2FA email verification fields to User model

Revision ID: c85adeb053b2
Revises: d06e8e6ae648
Create Date: 2025-07-20 10:10:29.897260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85adeb053b2'
down_revision = 'd06e8e6ae648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('appointment_type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_login')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('email_verification_expires')
        batch_op.drop_column('email_verification_code')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('email')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###
